language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # - "nightly" # currently points to 3.6-dev
  
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  
  global:
    - DJANGO_MANAGE_LOCATION="manage.py"
    - DJANGO_SETTINGS_MODULE="test_project.settings"

    


# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -U -q Django==$DJANGO_VERSION
  
# command to run tests
script: 
  - python manage.py makemigrations auth tests app2
  - python manage.py migrate --noinput
  - python manage.py test tests



notifications:
  email: false
